import java.util.InputMismatchException;
import java.util.Scanner;


public class Exception_Simple{
        public static void main (String[] ar)
        {
            //--------------------------------------------------------
            try{
                int divideByZero = 5/0;
            }
            catch(ArithmeticException e){
                System.out.println("Arithmetic Exception: cannot divide by zero." + e.getMessage());
            }
            finally{
                System.out.println("Finally block executed.");
            }
            //--------------------------------------------------------
            try{
                int[] arr = {1,2,3};
                System.out.println(arr[3]);
            }
            catch (ArrayIndexOutOfBoundsException e)
            {
                System.out.println("Caught array index out of bounds exception.");
            }
            catch (Exception e)
            {
                System.out.println("Caught general exception" + e.getMessage());
            }
            //--------------------------------------------------------
            String str = null;
            try{
                System.out.println(str.length());
            }
            catch(NullPointerException e){
                System.out.println("Null pointer exception caught.");
            }
            //--------------------------------------------------------
            Scanner scan = new Scanner(System.in);
            try{
                System.out.println("Enter first number: ");
                boolean num1 = scan.nextBoolean();
            }
            catch (InputMismatchException e){
                System.out.println("Error: Invalid Input");
            }
            finally{
                System.out.println("Finally block executed");
            }
            //--------------------------------------------------------

            //--------------------------------------------------------
        }
    
}
